### PR TITLE
Update macos target dependencies

### PR DESCRIPTION
**Pull request by ad0**
Simply updated MacOS dependencies since they were a few years behind.

### CODE REVIEW

**Comment by ad0** [comment]
In fact it is now more than a simple dependencies bump since it replace deprecated `mach` lib by its successor `mach2`.

**Comment by jczuluag** [comment]
> In fact it is now more than a simple dependencies bump since it replace deprecated `mach` lib by its successor `mach2`.

@ad0 , thanks for fixing this. Let me know if this is ready for review or not.

**Comment by ad0** [comment]
For now mach2 seems to be more or less a fork of mach so no big changes to make here.
So this is ready for review !

**Review by jczuluag — APPROVED** [review]
Thanks for this contribution @ad0.

**Comment by paulvt** [comment]
Would it be possible to cut a new release that includes this change. This would solve [RUSTSEC-2020-0168](https://rustsec.org/advisories/RUSTSEC-2020-0168) for projects that depend on this crate. Thanks in advance!

**Comment by paulvt** [comment]
Well, there is also this dependency on `io-kit-sys` version 0.1.0 which depends on an even old version of `mach`, so a dependency bump of `io-kit-sys` to version 0.4.1 (which also switches to the `mach2` crate) is also necessary to really solve the security advisory.

**Pull request merged**
