### PR TITLE
Change to version 8.1

### PR DESCRIPTION
**Pull request by jrgerber**
With the recent breaking change and other improvements this is a good point to version and then update the crate.

@mulark let me know what you think of the change I made to your cache PR #94.

### CODE REVIEW

**Review by mulark — APPROVED** [review]

**Comment by jrgerber** [comment]
@mulark Woops, too late to change it to 0.9.0 now.  I forgot the breaking change rules.  Crossing my fingers...

**Comment by jrgerber** [comment]
https://semver.org/
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.

**Comment by mulark** [comment]
I thought about that but figured that before 1.0 every change is considered breaking anyway.

**Comment by mulark** [comment]
Hmm, Cargo doesn't follow semver here 
```This compatibility convention is different from SemVer in the way it treats versions before 1.0.0. While SemVer says there is no compatibility before 1.0.0, Cargo considers 0.x.y to be compatible with 0.x.z, where y ≥ z and x > 0.```

**Comment by jrgerber** [comment]
OK it's a cargo rule.  That's what I recalled as doing last year when I last worked on this project but couldn't recall why.  I see someone is indeed following that rule (stats overview https://crates.io/crates/smbios-lib) because 8.1 is seeing a jump already.  Hopefully nothing broke for anyone.  I may need to put something on the README.md stating this project will version to the Cargo rules.

**Pull request merged**
