### PR TITLE
Fix device function number parse

### PR DESCRIPTION
**Pull request by mulark**

### CODE REVIEW

**Review by jrgerber — APPROVED** [review]
Fantastic.  I searched for >> to see if there are any other precedence cases and it appears this is the only one.

**Comment by mulark** [comment]
Yea I tried looking for anything where we bitwise and and then also don't have a closing paren. Seems like every instance like that was fine. Didn't try to find any that could have spanned any lines, so may have missed there.

**Comment by jrgerber** [comment]
Woops, this broke a test that was written incorrectly.

---- structs::types::onboard_devices_extended_information::tests::unit_test stdout ----
thread 'structs::types::onboard_devices_extended_information::tests::unit_test' panicked at 'assertion failed: `(left == right)`
  left: `31`,
 right: `30`', src/structs/types/onboard_devices_extended_information.rs:145:17

```rust
        let struct_type41 = vec![
            0x29, 0x0B, 0x3B, 0x00, 0x01, 0x85, 0x01, 0x00, 0x00, 0x00, 0xFE, 0x69, 0x32, 0x31,
            0x39, 0x00, 0x00,
        ];

// 0xFE is the device/function value which should be 0b11111 (0n31) and 0b110 (0n6)
// The test is incorrectly looking for 0n30:
        match test_struct.device_function_number().unwrap() {
            DeviceFunctionNumber::Number { device, function } => {
                assert_eq!(device, 30);
                assert_eq!(function, 6);
            }
```
```

**Comment by mulark** [comment]
My bad, didn't realize CI wasn't present on this repo so didn't try to run tests.

**Pull request merged**
